### ISSUE TITLE
Do not replace | characters with \x01 if separator is \x01

### ISSUE THREAD

**Issue by jonfreedman** [logotype/fixparser#3]
If we parse a fix string which is already separated with `\x01` characters [FIXParser.js#L26](https://github.com/logotype/fixparser/blob/master/src/FIXParser.js#L26) incorrectly replaces these with additional `\x01` characters which then result in items with tag NaN.  It would be preferable to make the split character an optional argument to FIXParser#parse and not perform this replacement.

https://codepen.io/anon/pen/vZXRNV

**Comment by logotype** [comment]
Hi
Thanks for spotting this! I obviously should have added this test case previously. This is fixed in 1.6.3 (published to NPM). The library now supports dynamically determining the separator.
There might be some difference in performance now, but i'll look into that in a subsequent release.

Thanks!

**Comment by jonfreedman** [comment]
Hi, I'm afraid your implementation sill has a bug, for the latest FIX spec tag 8 may not be 7 characters e.g. 8=FIXT.1.1
